version: 2
updates:
  - package-ecosystem: 'npm'
    directory: "/ui/houston"
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
