version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui/houston"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      dev-dependencies:
        dependency-type: "development"
        applies-to: version-updates
      runtime-dependencies:
        dependency-type: "production"
        applies-to: version-updates
  
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "hourly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      dev-dependencies:
        dependency-type: "development"
        applies-to: version-updates
      runtime-dependencies:
        dependency-type: "production"
        applies-to: version-updates
